
# HTTP Server
server:
  port: 1111

# Eureka Configuration Properties
eureka:
  client:
    #registerWithEureka: true
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0


spring:
  application:
    name: eureka server
  boot:
    admin:
      context-path: /admin


info:
  component: eureka server
